# Generated by Django 3.1.1 on 2020-09-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
