# Generated by Django 3.1.1 on 2020-09-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_stock_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_History2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True)),
                ('Open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('High', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ticker', models.CharField(max_length=10)),
            ],
        ),
    ]
