# Generated by Django 3.1.1 on 2020-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_stock_history2'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_history2',
            name='Counter',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
